// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDK66SoZkLzFHAyq1bbOCELszfAPa5rBIs',
    appId: '1:390851858388:web:822f2d162727824a7a5041',
    messagingSenderId: '390851858388',
    projectId: 'zworkflow-zaramell',
    authDomain: 'zworkflow-zaramell.firebaseapp.com',
    storageBucket: 'zworkflow-zaramell.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDK66SoZkLzFHAyq1bbOCELszfAPa5rBIs',
    appId: '1:390851858388:android:822f2d162727824a7a5041',
    messagingSenderId: '390851858388',
    projectId: 'zworkflow-zaramell',
    storageBucket: 'zworkflow-zaramell.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAblaDNy3PPjToCSQ-lZ5-5o0AOaMqnE2k',
    appId: '1:390851858388:ios:d0eb9eb4ef28a9407a5041',
    messagingSenderId: '390851858388',
    projectId: 'zworkflow-zaramell',
    storageBucket: 'zworkflow-zaramell.firebasestorage.app',
    iosBundleId: 'com.zaramella.zworkflow',
  );
}
